version: "3.6"
services:
  spark-master:
    image: chloeji/spark:latest
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - spark-network
    command: "start-master.sh --ip spark-master --webui-port 8080 --port 7077"

  spark-worker-1:
    image: chloeji/spark:latest 
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    networks:
      - spark-network
    command: "start-worker.sh --webui-port 8081 spark://spark-master:7077"


  spark-worker-2:
    image: chloeji/spark:latest
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8082"
    networks:
      - spark-network
    command: "start-worker.sh --webui-port 8082 spark://spark-master:7077"

  networks:
    spark-network:
      driver: bridge
      ipam:
        driver: default 